### ISSUE TITLE
扫描二维码分享此文章

### ISSUE THREAD

**Issue by halfrost** [foru17/Yasuko#12]
这个接口可能有问题，显示不出来二维码了。看了一下博主的博客，这个二维码好像也显示不出来了。

**Comment by foru17** [comment]
我原先的二维码接口已经下线了，建议可以换成新的第三方二维码接口 http://qr.liantu.com/api.php?text=

**Comment by halfrost** [comment]
好像你的博客可以显示出二维码了，原先的接口又上线了？还是说原来接口换新的了？？？

**Comment by foru17** [comment]
那个接口是我自己写的简单的服务,昨天服务器挂了，重启忘记启动服务了。

**Comment by halfrost** [comment]
额。。好吧。。。那谢谢大神修复了这个问题！！
